version = "2"

[run]
timeout = "5m"

[output.formats.text]
print-linter-name = true
print-issued-lines = true
colors = true

[linters]
settings.errcheck.exclude-functions = [
    "(io.Closer).Close",
    "(net.Conn).Close",
    "(*os.File).Close",
    "(*compress/gzip.Reader).Close",
    "(*database/sql.DB).Close",
    "(*database/sql.Stmt).Close",
    "(*database/sql.Tx).Rollback",
    "(*database/sql.Rows).Close",
    "(*github.com/calindra/rollups-base-reader/pkg/contracts.InputBoxInputAddedIterator).Close",
]
exclusions.paths = ["pkg/model/node_models.go"]
